CC = gcc
CFLAGS = -Wall 

all:ac-matrice ac-hachage genere-texte genere-mots 

ac-matrice: ac-matrice.c
	$(CC) $(CFLAGS) ac-matrice.c -o ac-matrice

ac-hachage: ac-hachage.c
	$(CC) $(CFLAGS) ac-hachage.c -o ac-hachage

genere-texte: genere-texte.c
	$(CC) $(CFLAGS) genere-texte.c -o genere-texte

genere-mots: genere-mots.c
	$(CC) $(CFLAGS) genere-mots.c -o genere-mots
	
